# Generated by Django 4.2.1 on 2023-06-26 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaperShop', '0004_products_stock_alter_products_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='lastName',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='users',
            name='name',
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(upload_to='vaperShop/products/'),
        ),
    ]
