# Generated by Django 4.2.1 on 2023-06-26 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaperShop', '0006_alter_users_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
