# Generated by Django 4.2.1 on 2023-06-27 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaperShop', '0007_alter_users_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
